import Head from 'next/head'
import Layout from '../components/layout'
import { Container, Row, Text, Spacer, Divider, Col, Grid, Button } from '@nextui-org/react';


import type { NextPage } from 'next';
import { useAddress } from '@thirdweb-dev/react';

const Home: NextPage = () => {

  const address = useAddress();

  return (
    <Layout>
      <div >
        <Head>
          <title>Test Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main>
          <Container fluid md gap={3}>
            <Row justify="center">
              <Text h1>Lens Testing Page</Text>
              <Spacer />
            </Row>
            <Spacer />
            <Divider />
            <Spacer />
            <Row>
              <Col>
                <Row>
                  <Text h3>This is a headline</Text>
                </Row>
                <Row>
                  <Text>Here is some Text</Text>
                  <Spacer />
                  <Text>Here is the address: {address}</Text>
                </Row>
                <Row>
                  <Button>Button!</Button>
                </Row>
              </Col>
            </Row>
            <Row>
              <Col>
                <Row>
                  <Text h3>Another Headline</Text>
                </Row>
                <Row>
                  <Text>More text lalala</Text>
                </Row>
              </Col>
            </Row>
          </Container>
        </main>
      </div>
    </Layout>
  )
}


export default Home;