import Head from 'next/head'
import Layout from '../components/layout'
import { Container, Row, Text, Spacer, Divider, Col, Grid, Button } from '@nextui-org/react';
import Web3 from 'web3';


import type { NextPage } from 'next';
import { useAddress } from '@thirdweb-dev/react';

const Home: NextPage = () => {

  const address = useAddress();

  const deploy = async () => {

    const web3 = new Web3(/* Ropsten or Mainnet HTTP RPC endpoint */)

    const contract = TruffleContract(Deployer)
    contract.setProvider(web3.currentProvider)

    const deployer = await contract.deployed()

    // deploy a new party (see Deployer.sol for parameter documentation)
    await deployer.deploy('My event', 0, 0, 0, oneweek, owneraddress, tokenaddress)

    const events = await promisify(deployer.contract.getPastEvents, deployer.contract)('NewParty')

    const { returnValues: { deployedAddress } } = events.pop()

    console.log(`New party contract deployed at: ${deployedAddress}`)
  }

  return (
    <Layout>
      <div >
        <Head>
          <title>Test Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main>
          <Container fluid md gap={3}>
            <Spacer />
            <Row justify="center">
              <Text h1>Main Page</Text>
              <Spacer />
            </Row>
            <Spacer />
            <Divider />
            <Spacer />
            <Row>
              <Col>
                <Row justify="center">
                  <Text h3>This is a headline</Text>
                </Row>
                <Row justify="center">
                  <Text>Here is some Text</Text>
                  <Spacer />
                  <Text>Here is the address: {address}</Text>
                </Row>
                <Row justify="center">
                  <Button onPress={deploy}>Button!</Button>
                </Row>
              </Col>
            </Row>
            <Row>
              <Col>
                <Row justify="center">
                  <Text h3>Another Headline</Text>
                </Row>
                <Row justify="center">
                  <Text>More text lalala</Text>
                </Row>
              </Col>
            </Row>
          </Container>
        </main>
      </div>
    </Layout>
  )
}


export default Home;